// frontend/src/components/form/FormField.tsx
import { FormEvent, FunctionComponent, useState } from "react";
import tinycolor from "tinycolor2";
import { SwatchesPicker } from "react-color";

interface CommonProps {
  type: "textarea" | "password" | "text" | "checkbox" | "radio" | "colour";
  placeholder?: string;
  label?: string;
  name: string;
  errors: string[];
  touched?: boolean;
  onTouched: () => void;
  options?: {
    value: string;
    label?: string;
  }[];
}

type CheckboxProps = {
  type: "checkbox";
  value: boolean;
  onChange: (val: boolean) => void;
  onInput: (val: boolean) => void;
} & CommonProps;

type RadioProps = {
  type: "radio";
  value: string;
  options: {
    value: string;
    label?: string;
  }[];
  onChange: (val: string) => void;
  onInput: (val: string) => void;
} & CommonProps;

type TextProps = {
  type: "textarea" | "password" | "text";
  value: string;
  onChange: (val: string) => void;
  onInput: (val: string) => void;
} & CommonProps;

type ColourProps = {
  type: "colour";
  value: string;
  onChange: (val: string) => void;
  onInput: (val: string) => void;
} & CommonProps;

type Props = TextProps | RadioProps | CheckboxProps | ColourProps;

const FormField: FunctionComponent<Props> = ({
  onTouched,
  touched,
  label,
  name,
  placeholder,
  errors,
  ...props
}) => {
  const [internalTouched, setInternalTouched] = useState(touched || false);

  const change = (e: FormEvent<HTMLInputElement>) => {
    if (props.type === "checkbox")
      props.onChange(Boolean(e.currentTarget.value));
    else props.onChange(e.currentTarget.value);
    if (touched !== undefined) onTouched();
    else setInternalTouched(true);
  };

  const input = (e: FormEvent<HTMLInputElement>) => {
    console.log(name, e.currentTarget.value);
    if (props.type === "checkbox")
      props.onInput(Boolean(e.currentTarget.value));
    else props.onInput(e.currentTarget.value);
  };

  // const updateColour = (e: ) => {
  //   if (props.type === "colour")
  //     props.onInput(e.colors.hex.substring(0, 7))
  // };

  return (
    <div className="form-field">
      <div className="input-container">
        <div className="label">{label}:</div>
        {(() => {
          if (props.type === "radio") {
            return (
              <div
                className="form-input"
                style={{
                  width: "100%",
                  textAlign: "start",
                  alignItems: "center",
                }}
              >
                {props.options.map((o, i) => {
                  return (
                    <div key={i}>
                      <input
                        id={name! + i}
                        value={o.value}
                        name={name}
                        type="radio"
                        onInput={input}
                        onChange={change}
                      />
                      {o.label ? o.label : o.value}
                    </div>
                  );
                })}
              </div>
            );
          } else if (props.type === "checkbox") {
            return (
              <div
                className="form-input"
                style={{
                  width: "100%",
                  height: "100%",
                  textAlign: "start",
                  alignItems: "center",
                }}
              >
                <input
                  placeholder={placeholder}
                  type={props.type}
                  value={String(props.value)}
                  name={name}
                  onInput={input}
                  onChange={change}
                />
              </div>
            );
          } else if (props.type == "colour") {
            return (
              <SwatchesPicker
                className="form-input"
                color={props.value}
                onChange={(c) => {
                  props.onChange(c.hex);
                }}
              />
            );
          } else {
            return (
              <div
                className="form-input"
                style={{
                  width: "100%",
                  height: "100%",
                  textAlign: "start",
                  alignItems: "center",
                }}
              >
                <input
                  placeholder={placeholder}
                  type={props.type}
                  value={props.value}
                  name={name}
                  onInput={input}
                  onChange={change}
                />
              </div>
            );
          }
        })()}
      </div>
      <div className="errors">
        {(touched === undefined ? internalTouched : touched) ? (
          <div>
            {errors.map((e, i) => {
              <div key={i}>{e}</div>;
            })}{" "}
          </div>
        ) : null}
      </div>
    </div>
  );
};

export default FormField;

// frontend/src/components/form/FormField.vue
<template>
  <div class="form-field">
    <div class="input-container">
      <div class="label">{{ label }}:</div>
      <div
        v-if="type === 'radio'"
        style="width: 100%; text-align: start; align-items: center"
      >
        <div v-for="(o, i) in options" :key="i" style="">
          <input
            :id="name! + i"
            :value="o.value !== undefined ? o.value : o"
            :name="name"
            type="radio"
            v-on:input="input"
            v-on:change="change"
          />
          {{ o.name ? o.name : o }}
        </div>
      </div>
      <div v-else-if="type === 'colour'">
        <ColorPicker
          :color="value"
          @color-change="updateColour"
          :visible-formats="['hex']"
          alpha-channel="hide"
        >
          <template v-slot:copy-button><div></div></template>
        </ColorPicker>
      </div>
      <div
        v-else
        style="
          width: 100%;
          height: 100%;
          text-align: start;
          align-items: center;
        "
      >
        <input
          :placeholder="placeholder"
          v-bind:type="type"
          :value="value"
          :name="name"
          v-on:input="input"
          v-on:change="change"
        />
      </div>
    </div>
    <div class="errors">
      <div v-if="touched || internalTouched">
        <div v-for="(error, index) in errors" :key="index">
          {{ error }}
        </div>
      </div>
      <div v-else-if="parentErrors">
        <div v-for="(error, index) in parentErrors" :key="index">
          {{ error }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { ColorPicker } from "vue-accessible-color-picker";
let emit = defineEmits(["change", "input"]);

let props = defineProps({
  placeholder: String,
  label: String,
  name: String,
  type: String,
  value: null,
  errors: Array,
  parentErrors: Array,
  options: Array,
  touched: Boolean,
});

let internalTouched = ref(false);

let change = (e: Event) => {
  emit("change", e);
  if (props.touched === undefined) internalTouched.value = true;
};
let input = (e: Event) => {
  emit("input", e);
};
let updateColour = (e: any) => {
  emit("input", { target: { value: e.colors.hex.substring(0, 7) } });
};
</script>

<style scoped>
.form-field {
  padding-bottom: 1em;
}

.label {
  text-align: end;
}

.input-container {
  gap: 1em;
  display: grid;
  grid-template-columns: 2fr 3fr;
  justify-items: right;
}

.radio-container {
  gap: 1em;
  display: grid;
  grid-template-columns: 2fr 3fr;
  justify-items: right;
}
</style>
