// frontend/src/components/form/FormComponent.tsx
import "./form.scss";
import * as Yup from "yup";

import {
  ChangeEvent,
  FormEvent,
  FunctionComponent,
  KeyboardEventHandler,
  ReactNode,
  useState,
} from "react";
import { mapObject } from "../../util/transform";
import FormField from "./FormField";

interface FieldDescription {
  type: "textarea" | "password" | "text" | "radio" | "checkbox" | "colour";
  label?: string;
  placeholder?: string;
}

type TextFieldDescription = {
  type: "textarea" | "password" | "text";
  initialValue?: string;
} & FieldDescription;

type RadioFieldDescription = {
  type: "radio";
  initialValue?: string;
  options: {
    value: string;
    label?: string;
  }[];
} & FieldDescription;

type CheckboxFieldDescription = {
  type: "checkbox";
  initialValue?: boolean;
} & FieldDescription;

type ColourFieldDescription = {
  type: "colour";
  initialValue?: string;
} & FieldDescription;

export type formFieldDescription =
  | TextFieldDescription
  | RadioFieldDescription
  | CheckboxFieldDescription
  | ColourFieldDescription;

export type FormDataType<Description> = {
  [Property in keyof Description]: Description[Property] extends {
    type: "checkbox";
  }
    ? boolean
    : string;
};

type Props<
  FieldsType extends {
    [key: string]: formFieldDescription;
  }
> = {
  fields: FieldsType;
  title?: string;
  validatorSchema?: Yup.AnySchema;
  initialErrors?: {
    [Property in keyof FieldsType]: string[];
  };
  children?: ReactNode | undefined;
  after?: ReactNode | undefined;
  onSubmit: (values: FormDataType<FieldsType>) => void;
};

const FormComponent = <
  FieldsType extends {
    [key: string]: formFieldDescription;
  }
>({
  children,
  after,
  fields,
  title,
  validatorSchema,
  initialErrors,
  onSubmit,
}: Props<FieldsType>) => {
  const [hasErrors, setHasErrors] = useState(false);
  const [formData, setFormData] = useState<FormDataType<FieldsType>>(
    mapObject(fields, (desc) => {
      if (desc.initialValue === undefined)
        return desc.type === "checkbox" ? false : "";
      return desc.initialValue;
    }) as FormDataType<FieldsType>
  );
  const [formErrors, setFormErrors] = useState<{
    [Property in keyof FieldsType]: string[];
  }>(initialErrors || mapObject(fields, () => []));
  const [formTouched, setFormTouched] = useState<{
    [Property in keyof FieldsType]: boolean;
  }>(mapObject(fields, () => false));

  async function validate(field: string | undefined) {
    if (!validatorSchema) return;
    const errors: {
      [Property in keyof FieldsType]: string[];
    } = mapObject(fields, () => []);
    try {
      validatorSchema.validateSync(formData, { abortEarly: false });
      setHasErrors(false);
    } catch (e: any) {
      let err = e as Yup.ValidationError;
      setHasErrors(true);
      if (err.inner) {
        let newErrors = err.inner as Yup.ValidationError[];
        newErrors.forEach((err) => {
          if (!err.path) {
            console.log(err.message);
            return;
          }
          let key = err.path as keyof FieldsType;
          errors[key] = errors[key].concat([err.message]);
        });
      }
    }
    setFormErrors(errors);
  }

  function setTouched(f: keyof FieldsType) {
    formTouched[f] = true;
    setFormTouched(formTouched);
  }

  let submit = async (e: FormEvent<HTMLButtonElement>) => {
    e.preventDefault();
    await validate(undefined);
    if (!hasErrors) {
      onSubmit(formData);
      reset();
    } else {
      setFormTouched(mapObject(fields, () => true));
    }
  };

  function reset() {
    setFormErrors(mapObject(fields, () => []));
    setFormTouched(mapObject(fields, () => false));
  }

  const onKeyUp: KeyboardEventHandler<HTMLFormElement> = (e) => {
    if (e.key == "Enter") onSubmit(formData);
    e.preventDefault();
  };

  return (
    <div className="form-container">
      <form onKeyUp={onKeyUp}>
        {children}
        <hr />
        <div className="fields">
          {Object.keys(fields).map((name: keyof FieldsType) => {
            const field = fields[name];
            const shared = {
              key: name as string,
              name: name as string,
              label: field.label,
              placeholder: field.placeholder,
              onInput: (e: string | boolean) => {
                validate(name as string);
                // formData[name] =
                //   e as FormDataType<FieldsType>[keyof FieldsType];
                //setFormData(formData);
              },
              onChange: (e: string | boolean) => {
                setTouched(name as string);
                const f = { ...formData };
                f[name] = e as FormDataType<FieldsType>[keyof FieldsType];
                setFormData(f);
                validate(name as string);
              },
              onTouched: () => {
                setTouched(name as string);
              },
              errors: formErrors[name],
            };
            switch (field.type) {
              case "radio":
                return (
                  <FormField
                    type={field.type}
                    value={formData[name] as string}
                    options={field.options}
                    {...shared}
                  />
                );
              case "checkbox":
                return (
                  <FormField
                    type={field.type}
                    value={formData[name] as boolean}
                    {...shared}
                  />
                );
              case "colour":
                return (
                  <FormField
                    type={field.type}
                    value={formData[name] as string}
                    {...shared}
                  />
                );
              default:
                return (
                  <FormField
                    type={field.type}
                    value={formData[name] as string}
                    {...shared}
                  />
                );
            }
          })}
          <button className="btn" disabled={hasErrors} onClick={submit}>
            Submit
          </button>
        </div>
        {after}
      </form>
    </div>
  );
};

export default FormComponent;

// frontend/src/components/Form/FormComponent.vue
<template>
  <form>
    <slot></slot>
    <hr />
    <div class="fields">
      <FormField
        v-for="(field, name) in fields"
        :key="name"
        :label="field.label"
        :placeholder="field.placeholder"
        :type="field.type"
        :value="fieldData[name]"
        v-on:input="(e) => {validate(name as string); fieldData[name] = e.target.value}"
        v-on:change="setTouched(name as string)"
        :touched="fieldTouched[name]"
        :errors="fieldErrors[name]"
        :parent-errors="parentErrors[name]"
      />
    </div>
    <input
      class="btn"
      v-bind:disabled="hasErrors"
      @click="
        async () => {
          await validate(undefined);
          if (!hasErrors) {
            $emit('submitted', fieldData);
            reset();
          } else {
            exposeErrors();
          }
        }
      "
      type="button"
      value="Submit"
    />
  </form>
  <slot name="after"></slot>
</template>

<script setup lang="ts">
import { ref, type Ref } from "vue";
import * as Yup from "yup";
import FormField from "./FormField.vue";

type tFields = {
  [key: string]: {
    type: "button" | "textarea" | "checkbox" | undefined;
    initialValue?: string | boolean;
    label?: string;
    placeholder?: string;
  };
};

defineEmits(["submitted"]);
const props = defineProps({
  fields: Object,
  title: String,
  validatorSchema: Object,
  parentErrors: null,
});

// Field Metadata
let fields = props.fields as tFields;

let fieldData: Ref<{ [key: string]: string | boolean }> = ref({});
let fieldErrors: Ref<{ [key: string]: string[] }> = ref({});
let fieldTouched: Ref<{ [key: string]: boolean }> = ref({});

for (var fieldName in fields) {
  fieldData.value[fieldName] = fields[fieldName].initialValue || "";
  fieldErrors.value[fieldName] = [];
  fieldTouched.value[fieldName] = false;
}

function setTouched(f: string) {
  fieldTouched.value[f] = true;
}

function reset() {
  fieldErrors.value = {};
  fieldTouched.value = {};

  let errors: { [key: string]: string[] } = {};
  for (var fieldName in fields) {
    errors[fieldName] = [];
    fieldTouched.value[fieldName] = false;
  }
  fieldErrors.value = errors;
}

let exposeErrors = () => {
  for (var fieldName in fields) {
    fieldTouched.value[fieldName] = true;
  }
};

// Validation
let hasErrors = ref(false);
let validator = props.validatorSchema
  ? Yup.object(props.validatorSchema as any)
  : null;

async function validate(field: string | undefined) {
  for (var key in fieldErrors.value) {
    fieldErrors.value[key] = [];
  }
  if (!validator) return;
  try {
    validator.validateSync(fieldData.value, { abortEarly: false });
    if (field) fieldErrors.value[field] = [];
    hasErrors.value = false;
  } catch (e: any) {
    let err = e as Yup.ValidationError;
    hasErrors.value = true;
    if (err.inner) {
      let newErrors = err.inner as Yup.ValidationError[];
      newErrors.forEach((err) => {
        if (!err.path) {
          console.log(err.message);
          return;
        }
        fieldErrors.value[err.path] = fieldErrors.value[err.path].concat([
          err.message,
        ]);
      });
    }
  }
}
</script>

<style scoped>
* + hr {
  margin-top: 1em;
}

.fields {
  margin-top: 1em;
}

form {
  padding: 1em 0.5em;
  background-color: var(--color-background-mute);
  max-width: 60ch;
  margin: 1em;
  padding: 2em;
}
</style>
