// frontend/src/views/world/NoteExplorer.vue
<template>
  <div v-if="fetching">Loading...</div>
  <div v-else-if="error">
    404 Folder not found <a @click="goBack" class="btn">go back</a>
  </div>
  <div v-else-if="data.folder === null">No Folder here</div>
  <div v-else>
    <div style="display: flex; gap: 0.5em">
      <router-link
        v-if="data.folder.parentFolder"
        class="btn"
        :to="`${data.folder.parentFolder.id}`"
        ><i class="fa fa-caret-left" aria-hidden="true"></i
      ></router-link>
      <div @click="createFolder = true" class="btn">
        <i class="fa fa-folder" aria-hidden="true"></i>+
      </div>
      <div @click="createDocument = true" class="btn">
        <i class="fa fa-file" aria-hidden="true"></i>+
      </div>
      <div
        style="background-color: brown"
        v-if="data.folder.parentFolder"
        class="btn"
        @click="deleteFolderModal = true"
      >
        Delete
      </div>
    </div>
    <h2
      v-if="data.folder.parentFolder"
      style="
        background-color: var(--color-background-mute);
        margin: 0.5em 0 0 0;
        box-shadow: 2px 1px 5px rgb(0.3, 0.3, 0.3, 0.2);
      "
    >
      {{ data.folder.name }}
    </h2>
    <div v-if="!$route.params.folderId" style="display: none">
      oof
      {{
        $router.push(`/world/${route.params.worldId}/folder/${data.folder.id}`)
      }}
    </div>
    <div class="explorer">
      <FolderIcon
        v-for="(f, i) in data.folder.subfolders"
        :key="f.id"
        :folder-id="f.id"
        :world-id="$route.params.worldId"
        @update-clicked="updateClicked(i)"
      >
      </FolderIcon>

      <DocumentIcon
        v-for="f in data.folder.documents"
        :key="f.id"
        :document-id="f.id"
        :world-id="$route.params.worldId"
      >
      </DocumentIcon>
    </div>
    <FolderPermissions
      :folderId="folderId"
      :worldId="$route.params.worldId as string"
      v-if="data.folder.parentFolder"
    ></FolderPermissions>
    <ModalComponent v-if="createFolder" @close="createFolder = false"
      ><CreateFolder @success="createFolder = false"></CreateFolder
    ></ModalComponent>
    <ModalComponent v-if="updateFolder" @close="updateFolder = null"
      ><UpdateFolder
        :folder="updateFolder"
        @success="updateFolder = null"
      ></UpdateFolder
    ></ModalComponent>
    <ModalComponent v-if="createDocument" @close="createDocument = false"
      ><CreateDocument @success="createDocument = false"></CreateDocument
    ></ModalComponent>
    <ModalComponent v-if="deleteFolderModal" @close="deleteFolderModal = false">
      <ConfirmComponent @no="deleteFolderModal = false" @yes="deleteFolder">
        <h2 style="max-width: 30ch; text-align: center; margin-bottom: 1em">
          Are you sure you want to delete your folder?
        </h2>
      </ConfirmComponent>
    </ModalComponent>
  </div>
</template>

<script setup lang="ts">
import { useQuery, gql, useMutation } from "@urql/vue";
import { computed, ref, type Ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import FolderIcon from "../../components/noteExplorer/FolderIcon.vue";
import DocumentIcon from "../../components/noteExplorer/DocumentIcon.vue";
import ModalComponent from "../../components/structure/ModalComponent.vue";
import CreateFolder from "../../components/noteExplorer/CreateFolder.vue";
import CreateDocument from "../../components/noteExplorer/CreateDocument.vue";
import UpdateFolder from "../../components/noteExplorer/UpdateFolder.vue";
import ConfirmComponent from "../../components/structure/ConfirmComponent.vue";
import FolderPermissions from "../../components/noteExplorer/FolderPermissions.vue";

const route = useRoute();
const router = useRouter();

let folderId = computed(() => {
  return route.params.folderId as string;
});
let worldId = computed(() => {
  return !folderId.value ? route.params.worldId : undefined;
});
let createFolder = ref(false);
let createDocument = ref(false);
let deleteFolderModal = ref(false);
let updateFolder: Ref<any> = ref(null);

const { fetching, data, error, executeQuery } = useQuery({
  query: gql`
    query Folder($id: String) {
      folder(id: $id) {
        id
        name
        colour
        edit {
          id
        }
        readOnly {
          id
        }
        readAccessLevel
        writeAccessLevel
        parentFolder {
          id
        }
        documents {
          id
          name
        }
        subfolders {
          id
          name
          colour
        }
      }
    }
  `,
  variables: {
    id: folderId,
  },
});

const deleteFolderMutation = useMutation(gql`
  mutation DeleteFolder($id: String!) {
    deleteFolder(id: $id) {
      id
      parentFolder {
        id
      }
    }
  }
`);

const goBack = () => {
  router.push(`/world/${route.params.worldId}/folder`);
  executeQuery({
    worldId: worldId.value,
    id: folderId.value,
  });
};

let deleteFolder = () => {
  deleteFolderMutation.executeMutation({ id: folderId.value }).then((e) => {
    if (e.data.deleteFolder) {
      router.push(`${data.value.folder.parentFolder.id}`);
      deleteFolderModal.value = false;
    }
  });
};

let updateClicked = (i: number) => {
  console.log(data.value.folder.subfolders[i]);
  updateFolder.value = data.value.folder.subfolders[i];
};
</script>

<style scoped>
.explorer {
  display: grid;
  grid-template-columns: repeat(auto-fit, 9em);
  grid-auto-rows: 9em;
  gap: 0.5em;
  margin-bottom: 1em;
}
</style>

// frontend/src/views/world/NoteExplorer.tsx
import { FunctionComponent, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import CreateDocument from "../../components/noteExplorer/CreateDocument";
import CreateFolder from "../../components/noteExplorer/CreateFolder";
import DocumentIcon from "../../components/noteExplorer/DocumentIcon";
import FolderIcon from "../../components/noteExplorer/FolderIcon";
import FolderPermissions from "../../components/noteExplorer/FolderPermissions";
import FolderTree, {
  ObjectBundle,
  ObjectTypes,
} from "../../components/noteExplorer/FolderTree";
import UpdateFolder from "../../components/noteExplorer/UpdateFolder";
import ConfirmComponent from "../../components/structure/ConfirmComponent";
import ModalComponent from "../../components/structure/ModalComponent";
import {
  Folder,
  useDeleteFolderMutation,
  useFolderQuery,
  useMoveFolderMutation,
  useWorldQuery,
} from "../../generated/graphql-components";
import "./worldView.scss";

type Props = {};

const NoteExplorer: FunctionComponent<Props> = ({}) => {
  const params = useParams();
  const navigate = useNavigate();

  const [createFolderModal, setCreateFolderModal] = useState(false);
  const [createDocumentModal, setCreateDocumentModal] = useState(false);
  const [jumpToModal, setJumpToModal] = useState(false);
  const [deleteFolderModal, setDeleteFolderModal] = useState(false);
  const [updateFolder, setUpdateFolder] = useState<{
    id: string;
    name: string;
    colour: string;
  } | null>(null);

  const [{ fetching, data, error }, executeQuery] = useFolderQuery({
    variables: {
      id: params.folderId!,
    },
  });
  const [_, deleteFolderMutation] = useDeleteFolderMutation();

  const [moveDocumentModal, setMoveDocumentModal] = useState(false);

  const [, moveMutation] = useMoveFolderMutation();

  const moveDocument = (select: ObjectBundle) => {
    if (select.type === "document") return;
    moveMutation({
      folderId: params.documentId!,
      parentFolderId: select.id,
    });
    setMoveDocumentModal(false);
  };

  if (fetching) return <div>Loading...</div>;
  if (!data || !data.folder || error) return <div>{JSON.stringify(error)}</div>;

  let deleteFolder = () => {
    deleteFolderMutation({ id: params.folderId! }).then((e) => {
      if (e.data?.deleteFolder) {
        navigate(`../folder/${data.folder!.parentFolder?.id}`);
        setDeleteFolderModal(false);
      }
    });
  };

  let updateClicked = (i: number) => {
    console.log(data.folder!.subfolders[i]);
    setUpdateFolder(data.folder!.subfolders[i]);
  };

  const jumpTo = (s: ObjectBundle) => {
    if (s.type === ObjectTypes.Document) navigate(`../document/${s.id}`);
    else if (s.type === ObjectTypes.Folder) navigate(`../folder/${s.id}`);
  };
  return (
    <div>
      <div style={{ display: "flex", gap: "0.5em" }}>
        {data.folder.parentFolder ? (
          <Link
            className="btn"
            to={`../folder/${data.folder.parentFolder!.id}`}
          >
            <i className="fa fa-caret-left" aria-hidden="true"></i>
          </Link>
        ) : null}

        <div onClick={() => setCreateFolderModal(true)} className="btn">
          <i className="fa fa-folder" aria-hidden="true"></i>+
        </div>
        <div onClick={() => setCreateDocumentModal(true)} className="btn">
          <i className="fa fa-file" aria-hidden="true"></i>+
        </div>
        <div onClick={() => setJumpToModal(true)} className="btn">
          <i className="fa fa-align-left" aria-hidden="true"></i>
        </div>
        {data.folder.parentFolder && data.folder.editable ? (
          <div className="btn" onClick={() => setMoveDocumentModal(true)}>
            Move
          </div>
        ) : null}
        {data.folder.parentFolder && data.folder.editable ? (
          <div
            style={{ backgroundColor: "brown" }}
            className="btn"
            onClick={() => setDeleteFolderModal(true)}
          >
            Delete
          </div>
        ) : null}
      </div>
      {data.folder.parentFolder ? (
        <h2
          style={{
            backgroundColor: "var(--color-background-mute)",
            margin: "0.5em 0 0 0",
            boxShadow: "2px 1px 5px rgb(0.3, 0.3, 0.3, 0.2)",
          }}
        >
          {data.folder.name}
        </h2>
      ) : null}
      <div className="explorer">
        {data.folder.subfolders.map((folder, i) => {
          return (
            <FolderIcon
              key={folder.id}
              folderId={folder.id}
              onUpdateClicked={() => updateClicked(i)}
            />
          );
        })}

        {data.folder.documents.map((folder, i) => {
          return <DocumentIcon key={folder.id} documentId={folder.id} />;
        })}
      </div>
      {data.folder.parentFolder ? (
        <FolderPermissions
          folderId={params.folderId!}
          worldId={params.worldId!}
        ></FolderPermissions>
      ) : null}
      {createFolderModal ? (
        <ModalComponent
          close={() => {
            setCreateFolderModal(false);
          }}
        >
          <CreateFolder
            onSuccess={() => setCreateFolderModal(false)}
            worldId={params.worldId!}
            parentFolderId={params.folderId!}
          />
        </ModalComponent>
      ) : null}
      {createDocumentModal ? (
        <ModalComponent
          close={() => {
            setCreateDocumentModal(false);
          }}
        >
          <CreateDocument
            onSuccess={() => setCreateDocumentModal(false)}
            worldId={params.worldId!}
            parentFolderId={params.folderId!}
          />
        </ModalComponent>
      ) : null}
      {jumpToModal ? (
        <ModalComponent close={() => setJumpToModal(false)}>
          <FolderTree
            worldId={params.worldId!}
            showDocuments={true}
            onSelect={jumpTo}
            before={<h2>Jump To</h2>}
            after={
              <div className="btn" onClick={() => setJumpToModal(false)}>
                Cancel
              </div>
            }
          ></FolderTree>
        </ModalComponent>
      ) : null}
      {updateFolder ? (
        <ModalComponent close={() => setUpdateFolder(null)}>
          <UpdateFolder
            folder={updateFolder}
            onSuccess={() => setUpdateFolder(null)}
          ></UpdateFolder>
        </ModalComponent>
      ) : null}
      {deleteFolderModal ? (
        <ModalComponent close={() => setDeleteFolderModal(false)}>
          <ConfirmComponent
            no={() => setDeleteFolderModal(false)}
            yes={deleteFolder}
          >
            <h2
              style={{
                maxWidth: "30ch",
                textAlign: "center",
                marginBottom: "1em",
              }}
            >
              Are you sure you want to delete your folder?
            </h2>
          </ConfirmComponent>
        </ModalComponent>
      ) : null}
      {moveDocumentModal ? (
        <ModalComponent close={() => setMoveDocumentModal(false)}>
          <h2>Move</h2>
          <FolderTree
            worldId={params.worldId!}
            showDocuments={false}
            onSelect={moveDocument}
          ></FolderTree>
          <div className="btn" onClick={() => setMoveDocumentModal(false)}>
            Cancel
          </div>
        </ModalComponent>
      ) : null}
    </div>
  );
};

export default NoteExplorer;
