// frontend/src/views/world/UserManagementView.vue
<template>
  <div v-if="fetching">Loading...</div>
  <div v-else-if="error">Oof</div>
  <div v-else>
    <div
      style="
        display: flex;
        flex-direction: column;
        gap: 1em;
        margin-bottom: 1em;
      "
    >
      <div v-for="u in data.world.roles" :key="u.id">
        <span style="font-weight: bold">{{ u.user.username }}</span>
        {{ u.level }}
      </div>
    </div>
    <Invite v-if="data.world.myRole === 'ADMIN'" />
  </div>
</template>

<script setup lang="ts">
import { useQuery, gql } from "@urql/vue";
import { useRoute } from "vue-router";
import Invite from "../../components/world/Invite.vue";

const route = useRoute();

const { fetching, data, error } = useQuery({
  query: gql`
    query World($id: String!) {
      world(id: $id) {
        id
        myRole
        roles {
          id
          user {
            id
            username
          }
          level
        }
      }
    }
  `,
  variables: {
    id: route.params.worldId,
  },
});
</script>

<style scoped></style>

// frontend/src/views/world/UserManagementView.tsx
import { useNavigate, useParams } from "react-router-dom";
import { FunctionComponent } from "react";
import { useWorldQuery } from "../../generated/graphql-components";
import Invite from "../../components/world/Invite";

type Props = {};

const UserManagementView: FunctionComponent<Props> = ({}) => {
  const params = useParams();

  const [{ fetching, data, error }] = useWorldQuery({
    variables: {
      id: params.worldId!,
    },
  });

  if (fetching) return <div>Loading...</div>;
  if (!data || !data.world || error) return <div>{JSON.stringify(error)}</div>;

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "1em",
        marginBottom: "1em",
      }}
    >
      {data.world.roles.map((role) => {
        return (
          <div key={role.id}>
            <span style={{ fontWeight: "bold", marginRight: "1em" }}>
              {role.user.username}
            </span>
            {role.level}
          </div>
        );
      })}
      <Invite v-if="data.world.myRole === 'ADMIN'" />
    </div>
  );
};

export default UserManagementView;
