// frontend/src/views/forms/Login.vue
<template>
  <div>
    <FormComponent
      v-on:submitted="submitLogin"
      :fields="{
        email: {
          initialValue: '',
          label: 'Email',
          placeholder: 'you@example.com',
        },
        password: {
          initialValue: '',
          label: 'Password',
          type: 'password',
          placeholder: 'password',
        },
      }"
      :validatorSchema="loginValidator"
      :parent-errors="formErrors"
    >
      <h2>Login</h2>
    </FormComponent>
  </div>
</template>

<script setup lang="ts">
import { gql, useMutation } from "@urql/vue";
import { ref, type Ref } from "vue";
import FormComponent from "@/components/Form/FormComponent.vue";
import * as Yup from "yup";
import { convertFieldErrors } from "@/util/errors";
import { useRouter } from "vue-router";

let router = useRouter();

let formErrors: Ref<{ [key: string]: string[] }> = ref({});

let loginValidator = {
  email: Yup.string().email("not a valid email").required(),
  password: Yup.string().required(),
};
// Login
let login = useMutation(gql`
  mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      fieldErrors {
        field
        message
      }
    }
  }
`);

let submitLogin = (loginFormValues: { email: string; password: string }) => {
  login
    .executeMutation(loginFormValues)
    .then((ret) => {
      let {
        data: {
          login: { fieldErrors },
        },
      } = ret;
      if (fieldErrors) {
        let val = convertFieldErrors(fieldErrors);
        formErrors.value = val;
      } else {
        router.push("/home");
      }
    })
    .catch((err) => {
      console.log(err);
    });
};
</script>

<style scoped></style>

// frontend/src/views/forms/Login.tsx
import * as Yup from "yup";
import { convertFieldErrors } from "../../util/errors";
import { FunctionComponent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useLoginMutation } from "../../generated/graphql-components";
import FormComponent, {
  FormDataType,
  formFieldDescription,
} from "../../components/form/FormComponent";
import { mapObject } from "../../util/transform";
import TitleComponent from "../../components/structure/TitleComponent";
type Props = {};

const Login: FunctionComponent<Props> = ({}) => {
  let navigate = useNavigate();
  const fields = {
    email: {
      type: "text" as "text",
      initialValue: "",
      label: "Email",
      placeholder: "you@example.com",
    },
    password: {
      initialValue: "",
      label: "Password",
      type: "password" as "password",
      placeholder: "password",
    },
  };
  let [formErrors, setFormErrors] = useState(
    mapObject(fields, () => [] as string[])
  );

  let loginValidator = Yup.object({
    email: Yup.string().email("not a valid email").required(),
    password: Yup.string().required(),
  });
  // Login
  let [login, executeLogin] = useLoginMutation();

  let submitLogin = (loginFormValues: FormDataType<typeof fields>) => {
    executeLogin(loginFormValues)
      .then((ret) => {
        if (!ret.data || !ret.data.login) return;
        let {
          data: {
            login: { fieldErrors },
          },
        } = ret;
        if (fieldErrors) {
          let val = convertFieldErrors(fieldErrors);
          Object.keys(val).forEach((key) => {
            formErrors[key as keyof typeof fields] =
              val[key as keyof typeof val]!;
          });
          setFormErrors(formErrors);
        } else {
          navigate("/home");
        }
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <div>
      <FormComponent
        fields={fields}
        onSubmit={submitLogin}
        validatorSchema={loginValidator}
        initialErrors={formErrors}
      >
        <TitleComponent text="Login" />
      </FormComponent>
    </div>
  );
};

export default Login;
