// Old/frontend/src/components/structure/ConfirmComponent.tsx
import { FunctionComponent } from "react";

type Props = {
  yes: () => void;
  no: () => void;
};

const ConfirmComponent: FunctionComponent<Props> = ({ yes, no }) => {
  return (
    <div>
      <slot>Are you sure?</slot>
      <div
        style={{ display: "flex", gap: "1em", justifyContent: "space-around" }}
      >
        <div className="btn" onClick={yes}>
          Yes
        </div>
        <div className="btn" onClick={no}>
          No
        </div>
      </div>
    </div>
  );
};

export default ConfirmComponent;

// frontend/src/components/structure/ConfirmComponent.vue
<template>
  <div>
    <slot>Are you sure?</slot>
    <div style="display: flex; gap: 1em; justify-content: space-around">
      <div class="btn" @click="$emit('yes')">Yes</div>
      <div class="btn" @click="$emit('no')">No</div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineEmits(["yes", "no"]);
</script>

<style scoped></style>
