// frontend/src/components/world/Invite.tsx
import { FunctionComponent, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useAssignUserRoleMutation } from "../../generated/graphql-components";
import { mapObject } from "../../util/transform";
import FormComponent from "../form/FormComponent";
import TitleComponent from "../structure/TitleComponent";

type Props = {};

const Invite: FunctionComponent<Props> = ({}) => {
  const params = useParams();
  const navigate = useNavigate();
  const [_, assignRole] = useAssignUserRoleMutation();

  const formFields = {
    email: {
      label: "Email",
      placeholder: "hoiti@toiti.com",
      initialValue: "",
      type: "text" as "text",
    },
    level: {
      label: "Role",
      placeholder: "hoiti@toiti.com",
      type: "radio" as "radio",
      options: [
        { name: "ADMIN", value: "ADMIN" },
        { name: "TRUSTED", value: "TRUSTED" },
        { name: "USER", value: "USER" },
        { name: "NONE", value: "" },
      ],
    },
  };

  let [parentErrors, setParentErrors] = useState(
    mapObject(formFields, () => [] as string[])
  );

  const submit = (s: any) => {
    assignRole({
      email: s.email,
      worldId: params.worldId!,
      level: s.level.length > 0 ? s.level : null,
    })
      .then((e) => {})
      .catch((err) => console.log(err));
  };

  return (
    <div className="invite-container">
      <FormComponent
        fields={formFields}
        onSubmit={submit}
        initialErrors={parentErrors}
        after={
          <Link className="btn" to="./">
            Back
          </Link>
        }
      >
        <TitleComponent text="Invite"> </TitleComponent>
      </FormComponent>
    </div>
  );
};

export default Invite;

// frontend/src/components/world/Invite.vue
<template>
  <div class="container">
    <FormComponent
      :fields="formFields"
      v-on:submitted="submit"
      :parent-errors="parentErrors"
      ><TitleComponent text="Invite"> </TitleComponent>
      <template v-slot:after
        ><router-link class="btn" to="./">Back</router-link></template
      ></FormComponent
    >
  </div>
</template>

<script setup lang="ts">
import { gql, useMutation } from "@urql/vue";
import { ref, type Ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import FormComponent from "@/components/form/FormComponent.vue";
import TitleComponent from "@/components/structure/TitleComponent.vue";

let parentErrors: Ref<{ [key: string]: string }> = ref({});

const route = useRoute();
const router = useRouter();
const assignRole = useMutation(gql`
  mutation AssignUserRole(
    $email: String!
    $worldId: String!
    $level: RoleLevel
  ) {
    assignWorldRole(worldId: $worldId, userEmail: $email, level: $level) {
      data {
        id
        level
      }
      errors
      fieldErrors {
        field
        message
      }
    }
  }
`);

const formFields = {
  email: {
    label: "Email",
    placeholder: "hoiti@toiti.com",
    initialValue: "",
  },
  level: {
    label: "Role",
    placeholder: "hoiti@toiti.com",
    type: "radio",
    options: ["ADMIN", "TRUSTED", "USER", { name: "NONE", value: "" }],
  },
};

const submit = (s: any) => {
  assignRole
    .executeMutation({
      email: s.email,
      worldId: route.params.worldId,
      level: s.level.length > 0 ? s.level : null,
    })
    .then((e) => {
      console.log(e);
    })
    .catch((err) => console.log(err));
};
</script>

<style scoped>
.container {
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;
  justify-items: center;
}
</style>
