// frontend/src/components/world/WorldSummaryBanner.vue
<template>
  <div v-if="fetching">Loading...</div>
  <div v-else-if="error">Oof</div>
  <div v-else>
    <router-link :to="'/world/' + uuid"> {{ data.world.name }} </router-link>
  </div>
</template>

<script setup lang="ts">
import { useQuery, gql } from "@urql/vue";

const props = defineProps(["uuid"]);
const { fetching, data, error } = useQuery({
  query: gql`
    query World($id: String!) {
      world(id: $id) {
        id
        name
      }
    }
  `,
  variables: {
    id: props.uuid,
  },
});
</script>

<style scoped></style>

// frontend/src/components/world/WorldSummaryBanner.tsx
import { FunctionComponent } from "react";
import { useNavigate } from "react-router-dom";
import { useWorldQuery } from "../../generated/graphql-components";
import "./world.scss";

type Props = {
  uuid: string;
};

const WorldSummaryBanner: FunctionComponent<Props> = ({ uuid }) => {
  const navigate = useNavigate();
  const [{ fetching, data, error }] = useWorldQuery({
    variables: {
      id: uuid,
    },
  });

  console.log(fetching, data);

  if (fetching) return <div>Loading...</div>;
  if (!data || !data.world || error) return <div>{JSON.stringify(error)}</div>;
  return (
    <div onClick={() => navigate("/world/" + uuid)} className="summary-banner">
      <h3>{data.world.name}</h3>
    </div>
  );
};

export default WorldSummaryBanner;
