// frontend/src/views/Home.tsx
import { FunctionComponent } from "react";
import { useMeQuery } from "../generated/graphql-components";
import { Link, Outlet, useNavigate } from "react-router-dom";
import SideHeader from "../components/structure/SideHeader";
import TitleComponent from "../components/structure/TitleComponent";
import LogoutButton from "../components/userControl/LogoutButton";

type Props = {};
const Home: FunctionComponent<Props> = ({}) => {
  const navigate = useNavigate();
  const [{ fetching, data, error }] = useMeQuery();
  if (fetching) return <div>Loading...</div>;
  if (!data || !data.me) {
    navigate("/landing");
    return <div></div>;
  }
  return (
    <SideHeader
      header={
        <div style={{ marginBottom: "1em" }}>
          <TitleComponent text="Home">
            Welcome {data.me.username}
          </TitleComponent>
        </div>
      }
      vCentered={false}
      rightFraction="3fr"
      dropdown={
        <div style={{ display: "grid", gap: "0.5em", marginTop: "1em" }}>
          <LogoutButton />
          <Link className="large-link" to={`worlds`}>
            <div className="auto-contrast">Worlds</div>
          </Link>
        </div>
      }
    >
      <Outlet />
    </SideHeader>
  );
};

export default Home;

// frontend/src/views/Home.vue
<script setup lang="ts">
import { gql, useQuery } from "@urql/vue";
import LogoutButton from "@/components/userControl/LogoutButton.vue";
import TitleComponent from "../components/structure/TitleComponent.vue";
import SideHeader from "../components/structure/SideHeader.vue";
import { RouterView } from "vue-router";

const { fetching, data, error } = useQuery({
  query: gql`
    {
      me {
        id
        username
      }
    }
  `,
});
</script>

<template>
  <div v-if="fetching">Loading...</div>
  <div v-else-if="error">Oof</div>
  <div v-else-if="data.me === null">{{ $router.push("/landing") }}</div>
  <SideHeader v-else>
    <template v-slot:header>
      <div style="margin-bottom: 1em">
        <TitleComponent style="margin-top: 1em" text="Home"
          >Welcome {{ data.me?.username }}
        </TitleComponent>
      </div>
    </template>
    <template v-slot:dropdown>
      <div style="display: grid; gap: 0.5em; margin-top: 1em">
        <LogoutButton class="large-link" />

        <router-link class="large-link" :to="`/home/worlds`"
          ><div class="auto-contrast">Worlds</div></router-link
        >
      </div>
    </template>
    <RouterView />
  </SideHeader>
</template>

<style scoped lang="scss"></style>
