// frontend/src/views/World.tsx
import "./World.scss";
import { FunctionComponent, useState } from "react";
import {
  useDeleteWorldMutation,
  useWorldQuery,
} from "../generated/graphql-components";
import { Link, Outlet, useNavigate, useParams } from "react-router-dom";
import SideHeader from "../components/structure/SideHeader";
import TitleComponent from "../components/structure/TitleComponent";
import LogoutButton from "../components/userControl/LogoutButton";
import ModalComponent from "../components/structure/ModalComponent";
import ConfirmComponent from "../components/structure/ConfirmComponent";

type Props = {};

const World: FunctionComponent<Props> = ({}) => {
  const navigate = useNavigate();
  const params = useParams();
  const [deleteWorldModal, setDeleteWorldModal] = useState(false);

  const [{ data, fetching, error }] = useWorldQuery({
    variables: {
      id: params.worldId!,
    },
  });

  const [_, deleteWorldMutation] = useDeleteWorldMutation();

  const deleteWorld = async (worldId: string) => {
    const res = await deleteWorldMutation({
      worldId,
    });
    if (res.data?.deleteWorld) navigate("/");
  };
  if (!data) return <div>Loading...</div>;
  if (error || !data.world) return <div>{JSON.stringify(error)}</div>;
  return (
    <div className="container">
      <SideHeader
        header={<TitleComponent text={data.world.name} />}
        rightFraction="3fr"
        vCentered={false}
        dropdown={
          <div style={{ display: "grid", gap: "0.5em", marginTop: "1em" }}>
            <Link to="/home" className="large-link">
              <div className="auto-contrast">Home</div>
            </Link>
            <LogoutButton />
            <Link className="large-link" to={`/world/${params.worldId}/users`}>
              <div className="auto-contrast">Users</div>
            </Link>
            <Link to={`/world/${params.worldId}/folder`} className="large-link">
              <div className="auto-contrast">Notes</div>
            </Link>
            <Link
              to={`/world/${params.worldId}/categories`}
              className="large-link"
            >
              <div className="auto-contrast">Categories</div>
            </Link>
            <Link
              to={`/world/${params.worldId}/templates`}
              className="large-link"
            >
              <div className="auto-contrast">Templates</div>
            </Link>
            <div
              v-if="data.world.myRole === 'ADMIN'"
              onClick={() => setDeleteWorldModal(true)}
              className="large-link"
              style={{ backgroundColor: "brown" }}
            >
              <div className="auto-contrast">Delete World</div>
            </div>
          </div>
        }
      >
        <Outlet />
      </SideHeader>
      {deleteWorldModal ? (
        <ModalComponent close={() => setDeleteWorldModal(false)}>
          <ConfirmComponent
            no={() => setDeleteWorldModal(false)}
            yes={() => deleteWorld(params.worldId as string)}
          >
            <h2
              style={{
                maxWidth: "30ch",
                textAlign: "center",
                marginBottom: "1em",
              }}
            >
              Are you sure you want to delete your world?
            </h2>
          </ConfirmComponent>
        </ModalComponent>
      ) : null}
    </div>
  );
};

export default World;

// frontend/src/views/World.vue
<template>
  <div v-if="fetching">Loading...</div>
  <div v-else-if="error">Oof</div>
  <div v-else class="container">
    <div>
      <div class="title"></div>
    </div>
    <SideHeader>
      <template v-slot:header>
        <TitleComponent :text="data.world.name" style="margin: 0 auto 0 0.5em">
        </TitleComponent>
      </template>
      <template v-slot:dropdown>
        <div style="display: grid; gap: 0.5em; margin-top: 1em">
          <router-link to="/home" class="large-link"
            ><div class="auto-contrast">Home</div></router-link
          >
          <LogoutButton class="large-link" />
          <router-link
            class="large-link"
            :to="`/world/${$route.params.worldId}/users`"
            ><div class="auto-contrast">Users</div></router-link
          >
          <router-link
            :to="`/world/${$route.params.worldId}/folder`"
            class="large-link"
            ><div class="auto-contrast">Notes</div></router-link
          >
          <router-link
            :to="`/world/${$route.params.worldId}/categories`"
            class="large-link"
            ><div class="auto-contrast">Categories</div></router-link
          >
          <router-link
            :to="`/world/${$route.params.worldId}/templates`"
            class="large-link"
            ><div class="auto-contrast">Templates</div></router-link
          >
          <div
            v-if="data.world.myRole === 'ADMIN'"
            @click="deleteWorldModal = true"
            class="large-link"
            style="background-color: brown"
          >
            <div class="auto-contrast">Delete World</div>
          </div>
        </div>
      </template>
      <RouterView />
    </SideHeader>
    <ModalComponent v-if="deleteWorldModal" @close="deleteWorldModal = false">
      <ConfirmComponent
        @no="deleteWorldModal = false"
        @yes="deleteWorld($route.params.worldId as string)"
      >
        <h2 style="max-width: 30ch; text-align: center; margin-bottom: 1em">
          Are you sure you want to delete your world?
        </h2>
      </ConfirmComponent>
    </ModalComponent>
  </div>
</template>

<script setup lang="ts">
import { useQuery, gql, useMutation } from "@urql/vue";
import { useRoute, RouterView } from "vue-router";
import TitleComponent from "../components/structure/TitleComponent.vue";
import LogoutButton from "../components/userControl/LogoutButton.vue";
import SideHeader from "../components/structure/SideHeader.vue";
import ModalComponent from "../components/structure/ModalComponent.vue";
import ConfirmComponent from "../components/structure/ConfirmComponent.vue";
import { ref } from "vue";
import router from "@/router";

const route = useRoute();
let deleteWorldModal = ref(false);
const { fetching, data, error } = useQuery({
  query: gql`
    query World($id: String!) {
      world(id: $id) {
        id
        name
        myRole
        users {
          id
          username
          role(worldId: $id) {
            id
            level
          }
        }
      }
    }
  `,
  variables: {
    id: route.params.worldId,
  },
});

const deleteWorldMutation = useMutation(
  gql`
    mutation DeleteWorld($worldId: String!) {
      deleteWorld(id: $worldId)
    }
  `
);

const deleteWorld = async (worldId: string) => {
  const res = await deleteWorldMutation.executeMutation({
    worldId,
  });
  if (res.data.deleteWorld) router.push("/");
};
</script>

<style scoped>
.title {
  display: flex;
  flex-direction: row;
  border-bottom: 1px solid var(--color-background-mute);
}

.home:hover {
  background-color: var(--color-secondary-soft);
}

main {
  padding: 1em;
}
</style>
