// frontend/src/components/noteExplorer/CreateDocument.vue
<template>
  <div class="container">
    <FormComponent
      :fields="formFields"
      v-on:submitted="submit"
      :parent-errors="parentErrors"
    >
      <TitleComponent text="Create Document"> </TitleComponent>
    </FormComponent>
  </div>
</template>

<script setup lang="ts">
import { gql, useMutation } from "@urql/vue";
import { ref, type Ref } from "vue";
import FormComponent from "@/components/form/FormComponent.vue";
import TitleComponent from "@/components/structure/TitleComponent.vue";
import { useRoute } from "vue-router";

let parentErrors: Ref<{ [key: string]: string }> = ref({});

const emit = defineEmits(["success"]);

const route = useRoute();
const createDocument = useMutation(gql`
  mutation CreateDocument(
    $name: String!
    $parentFolderId: String!
    $worldId: String!
  ) {
    createDocument(
      name: $name
      parentFolderId: $parentFolderId
      worldId: $worldId
    ) {
      data {
        id
        name
      }
      errors
      fieldErrors {
        field
        message
      }
    }
  }
`);

const formFields = {
  name: {
    label: "Name",
    placeholder: "Jensin",
    initialValue: "",
  },
};

const submit = (s: any) => {
  createDocument
    .executeMutation({
      name: s.name,
      parentFolderId: route.params.folderId,
      worldId: route.params.worldId,
    })
    .then((e) => {
      console.log(e);
      if (!e.data.createDocument.data) return;
      emit("success");
    })
    .catch((err) => console.log(err));
};
</script>

<style scoped>
.container {
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;
  justify-items: center;
}
</style>

// frontend/src/components/noteExplorer/CreateDocument.tsx
import { FunctionComponent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useCreateDocumentMutation } from "../../generated/graphql-components";
import { mapObject } from "../../util/transform";
import FormComponent from "../form/FormComponent";
import TitleComponent from "../structure/TitleComponent";
import "./noteExplorer.scss";

type Props = {
  parentFolderId: string;
  worldId: string;
  onSuccess: () => void;
};

const CreateDocument: FunctionComponent<Props> = ({
  parentFolderId,
  worldId,
  onSuccess,
}) => {
  let navigate = useNavigate();
  const formFields = {
    name: {
      label: "Name",
      type: "text" as "text",
      placeholder: "Cities",
      initialValue: "",
    },
  };
  let [formErrors, setFormErrors] = useState(
    mapObject(formFields, () => [] as string[])
  );

  const [_, createFolder] = useCreateDocumentMutation();

  const submit = (s: any) => {
    createFolder({
      name: s.name,
      parentFolderId: parentFolderId,
      worldId: worldId,
    })
      .then((e) => {
        if (!e.data?.createDocument?.data) return;
        onSuccess();
      })
      .catch((err) => console.log(err));
  };
  return (
    <div className="create-folder-container">
      <FormComponent
        fields={formFields}
        onSubmit={submit}
        initialErrors={formErrors}
      >
        <TitleComponent text="Create Document"> </TitleComponent>
      </FormComponent>
    </div>
  );
};

export default CreateDocument;
