// frontend/src/components/noteExplorer/UpdateFolder.vue
<template>
  <div class="container">
    <FormComponent
      :fields="formFields"
      v-on:submitted="submit"
      :parent-errors="parentErrors"
    >
      <TitleComponent text="Update Folder"> </TitleComponent>
    </FormComponent>
  </div>
</template>

<script setup lang="ts">
import { gql, useMutation } from "@urql/vue";
import { ref, type Ref } from "vue";
import FormComponent from "@/components/form/FormComponent.vue";
import TitleComponent from "@/components/structure/TitleComponent.vue";
import { useRoute } from "vue-router";

let parentErrors: Ref<{ [key: string]: string }> = ref({});

const props = defineProps(["folder"]);

const emit = defineEmits(["success"]);

const route = useRoute();
const updateFolder = useMutation(gql`
  mutation UpdateFolder($name: String!, $id: String!, $colour: String!) {
    updateFolder(name: $name, id: $id, colour: $colour) {
      id
      name
      colour
    }
  }
`);

const formFields = {
  name: {
    label: "Name",
    placeholder: "Jensin",
    initialValue: props.folder.name,
  },
  colour: {
    type: "colour",
    label: "Colour",
    initialValue: props.folder.colour,
  },
};

const submit = (s: any) => {
  console.log(s);
  updateFolder
    .executeMutation({
      name: s.name,
      id: props.folder.id,
      colour: s.colour,
    })
    .then((e) => {
      console.log(e);
      if (!e.data.updateFolder.data) return;
      emit("success");
    })
    .catch((err) => console.log(err));
};
</script>

<style scoped>
.container {
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 1fr;
  justify-items: center;
}
</style>

// frontend/src/components/noteExplorer/UpdateFolder.tsx
import { FunctionComponent, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  Folder,
  useUpdateFolderMutation,
} from "../../generated/graphql-components";
import { mapObject } from "../../util/transform";
import FormComponent from "../form/FormComponent";
import TitleComponent from "../structure/TitleComponent";

type Props = {
  folder: {
    id: string;
    name: string;
    colour: string;
  };
  onSuccess: () => void;
};

const UpdateFolder: FunctionComponent<Props> = ({ folder, onSuccess }) => {
  const navigate = useNavigate();
  const [_, updateFolder] = useUpdateFolderMutation();

  const formFields = {
    name: {
      label: "Name",
      type: "text" as "text",
      placeholder: "Jensin",
      initialValue: folder.name,
    },
    colour: {
      type: "colour" as "colour",
      label: "Colour",
      initialValue: folder.colour,
    },
  };

  const [formErrors, setFormErrors] = useState(
    mapObject(formFields, () => [] as string[])
  );

  const submit = (s: any) => {
    console.log(s);
    updateFolder({
      name: s.name,
      id: folder.id,
      colour: s.colour,
    })
      .then((e) => {
        if (!e.data?.updateFolder) return;
        onSuccess();
      })
      .catch((err) => console.log(err));
  };

  return (
    <div className="update-folder-container">
      <FormComponent
        fields={formFields}
        onSubmit={submit}
        initialErrors={formErrors}
      >
        <TitleComponent text="Update Folder"> </TitleComponent>
      </FormComponent>
    </div>
  );
};

export default UpdateFolder;
